// MODULE GENE READ NVC RSEQC

@preserve
rseqc_read_NVC_gfu =
{
    var pretend : false

    doc title: "Rseqc quality control of bam files: read_quality",
        desc: """
            This module is used to check the nucleotide composition bias.
            Due to random priming, certain patterns are over represented at the beginning (5’end) of reads.
            This bias could be easily examined by NVC (Nucleotide versus cycle) plot.
            NVC plot is generated by overlaying all reads together, then calculating nucleotide
            composition for each position of read (or each sequencing cycle).
            In ideal condition (genome is random and RNA-seq reads is randomly sampled from genome),
            we expect A%=C%=G%=T%=25% at each position of reads.
        """,
        constrains: "I am forcing export of site-packages to get qcmodule.",
        author: "davide.rambaldi@gmail.com"

    transform("NVC_plot.pdf","NVC_plot.r","NVC.xls")
    {
        def command = """
            $READNVC -i $input.bam -o $input.prefix;
        """

        if (pretend)
        {
            println """
                INPUT:   $input
                OUTPUTS: $output1 $output2 $output3
                COMMAND: $command
            """

            command = """
                echo "INPUT: $input" > $output1;
                echo "INPUT: $input" > $output2;
                echo "INPUT: $input" > $output3;
            """
        }
        exec command
    }
    forward input.bam
}
